export const UPDATE_SEARCH_USER = 'UPDATE_SEARCH_USER'
export const UPDATE_CHOOSEN_USER = 'UPDATE_CHOOSEN_USER'
export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST'
export const UPDATE_TITLE = 'UPDATE_TITLE'